Package as a nix flake, fetch grammars and queries from Helix.
hadronized/kak-tree-sitter pull request #200
Opened 2023-12-30 02:23 UTC by igor-ramazanov

Depend on `helix` sources to fetch and build `tree-sitter` grammars and queries. Also, use `helix` `tree-sitter` queries to generate the `config.toml`.

Had to update the `kak-tree-sitter-config` to be able to embed built-in grammars and queries. The new logic now is: try to load first from `XDG_*`, and fallback to built-in ones from `helix` if failed to load.

To try out, ensure `nix` installed with `flakes` enabled, and then:
```console
$ nix run github:igor-ramazanov/kak-tree-sitter/nix-flake -- --help

Usage: kak-tree-sitter [OPTIONS]
Options:
  -k, --kakoune
          Whether we start from Kakoune and then we should issue an initial request for setup
  -s, --server
          Start the server, if not already started
  -d, --daemonize
          Try to daemonize, if not already done
      --session <SESSION>
          Kakoune session to connect to
  -c, --client <CLIENT>
          Kakoune client to connect with, if any
  -r, --request <REQUEST>
          JSON-serialized request
  -v, --verbose...
          Verbosity.
          Can be accumulated to get more verbosity. Without this flag, logging is disabled. Then, for each applicaton of the flag, the obtained verbosity follows this order: error, warn, info, debug, trace. Thus, if you use -v, you will only get error messages. If you use -vv, you will also see warnings. The maximum verbosity is achieved with -vvvvv for trace logs.
  -h, --help
          Print help (see a summary with '-h')
  -V, --version
          Print version
```

2024-01-15 10:21 UTC, phaazon commented
I like that! I’ll try to review on my spare-time later. Thanks!

2024-02-10 10:16 UTC, phaazon approved these changes
I’m fine with the change; thanks! Just one thing: may you add some information that I could include in the wiki to explain how to install from Nix? Thanks!

2024-02-10 10:40 UTC, phaazon requested changes

2024-02-10 10:40 UTC, phaazon commented on kak-tree-sitter-config/src/lib.rs
> +      .map(|dir| dir.join("share/kak-tree-sitter"))
```suggestion
    std::env::current_exe()
      .ok()?
      .parent()?
      .parent()
      .map(|dir| dir.join("share/kak-tree-sitter"))
```

2024-02-10 10:40 UTC, phaazon commented on kak-tree-sitter-config/src/lib.rs
> +        Err(_) => builtin,
You can merge those.

2024-02-11 11:24 UTC, igor-ramazanov commented
Thanks for the review!

Yes, I'll add the wiki information.

Also, one user in Discord reported of some issue running it on NixOS: https://discord.com/channels/717163870724161556/717166088474984478/1200817299972698112

So, I'd like to try to debug and reproduce it first

2024-02-17 19:58 UTC, igor-ramazanov commented
Honestly, I am not sure if it was a good idea to put the logic of borrowing Helix grammars using Nix.

Perhaps, this logic should be in the `ktsctl`.

2024-02-19 06:18 UTC, postsolar commented on flake.nix
> +      grammars = pkgs.callPackage (import ./gen-grammars.nix {inherit helix;}) {};
If I understood it right, `gen-grammars.nix` function only needs the Helix repo to read its `languages.toml`. What if instead we just fetch that specific file to reduce the dependency? Maybe even fetch both Helix' `languages.toml` and `grammars.nix`, import the grammars function and call its package, then link what it produced? This would eliminate the need for `gen-grammars.nix` altogether.
This is more of a "what if" question, I'm not saying I'm hard sold on this.

2024-03-16 23:29 UTC, igor-ramazanov commented
The main branch moved forward, and now there are a bunch of conflicts which I'm struggling to resolve.

2024-03-16 23:51 UTC, igor-ramazanov commented on flake.nix
> +      grammars = pkgs.callPackage (import ./gen-grammars.nix {inherit helix;}) {};
That's right. It's been a long time already, and I don't remember why I did it the way I did. I think the bigger issue is to get this PR merged, and then open other PRs as optimizations.

The main branch already moved quite far, and I don't feel motivated in resolving conflicts and the writing the requested documentation (it's confusing, probably, people who know what Nix flakes are already know how to use them).

2024-03-16 23:59 UTC, igor-ramazanov commented
> Honestly, I am not sure if it was a good idea to put the logic of borrowing Helix grammars using Nix.

Because, the resulting package is inconsistent with the packages to be installed by other means. In my opinion packages should be consistent with each other, and fetching Helix grammars should be done in the project itself.

2024-03-16 23:59 UTC, closed without merging

2024-03-17 00:01 UTC, igor-ramazanov commented
I'll keep the branch in my fork open, in case if there're people depending on it.
However, I recommend copying the code, as I don't guarantee that it'll exist in the future.