Refactors and enhancements from my develop branch.
hadronized/kak-tree-sitter pull request #231
Opened 2024-02-15 11:35 UTC by topisani

While working on #212 and integrating kts in my workflow, I made some refactors and improvements on my own develop branch. I would like to keep working on kts, but I also don't want to further fracture the efforts, so i hope we can find a way to merge some of this.

Other than what is already in #212, this includes:

## Features:
 - Get defined faces from kakoune automatically using `debug faces`. This works, and removes the need of defining the available highlight groups in `config.toml`, but it has a few drawbacks:
   - currently, it isnt run automatically. There is no hook for changing colorscheme, so its hard to find the correct hook. I have it run once on startup in my own setup.
   - It parses the `*debug*` buffer, which works fine, but means that it fills lots of lines into the debug buffer every time it runs. I would like to contribute something to kakoune that improves this, possibly just a `debug -to-file`, or similar.
 - builds on top of #212 to make textobjects multiple selections compatible in a performant way.

## Enhancements
 - Only request highlighting if the buffer has changed (based on timestamp)
 - Improved handling of crashed/stopped servers by deleting the fifos when the server stops, and handling non-existing fifos when sending requests. When a new server is started, the clients reconnect and reinitialize automatically.
 - Minor: Add documentation comment highlighting to cpp files (compatible with existing faces)

## Refactoring
 - Split `server.rs` out into a few submodules
 - Move the handling of individual commands from `server` to `handler`
 - Use a `RequestMeta` type to simplify handling common request data (client, buffer, lang, timestamp)
 - Split `static.kak` into multiple files
 - Add `kak-tree-sitter-send-cmd` and `kak-tree-sitter-send-buf` helpers in `base.kak`
 - Use a shell block instead of kakoune options to define the colors for the default theme.
 - Use `%exp{}` blocks for request formatting instead of escaping in `"` strings.

All kakscript still uses shell blocks as little as possible (no shell blocks were added).

2024-02-16 22:42 UTC, phaazon commented
Thanks! Should we close #212 and superseded by this current one?

2024-02-16 23:29 UTC, phaazon requested changes
It’s an interesting PR that I wish we could merge ASAP. However, a couple of things:

- I left a bunch of suggestions of things to change.
- Some questions / nitpicking.
- You renamed / moved a lot of things and I struggle to understand why. I think it’s not needed _for now_ and you should probably focus on implementing a feature. You moved a lot of symbols that have nothing to do with textobjects, making reviewing longer and harder, and breaking a bit history search (i.e. I very often `git blame` inside my editor, and seeing the same commit all over the place is not good).

2024-02-16 23:29 UTC, phaazon commented on kak-tree-sitter/rc/features.kak
> +# This command does a couple of things, among removing the « default » highlighting (Kakoune based) of the buffer and
I’m not sure where you remove it?

2024-02-16 23:29 UTC, phaazon commented on kak-tree-sitter/src/error.rs
> +  CannotParseBuffer,
Could be worth it to add the name of the buffer in the error.

2024-02-16 23:29 UTC, phaazon commented on kak-tree-sitter/src/error.rs
> +  InternalError { err: String },
Still not a fan of such a vague error type. 🙂

2024-02-16 23:29 UTC, phaazon commented on kak-tree-sitter/src/handler.rs
> +      SessionCmd::DeclareFaces { faces } => {
I like that idea; it should easy everything.

2024-02-16 23:29 UTC, phaazon commented on kak-tree-sitter/src/handler.rs
> +      meta.timestamp
For a debug log, I think you can just `{meta:#?}`; it’s fine.

2024-02-16 23:29 UTC, phaazon commented on kak-tree-sitter/src/request.rs
> +pub enum GlobalRequest {
I’m not sure why you renamed it `GlobalRequest`?

2024-02-16 23:29 UTC, phaazon commented on kak-tree-sitter/src/response.rs
> +        ranges,
```suggestion
        timestamp,
        ranges,
        ..
```

2024-02-16 23:29 UTC, phaazon commented on kak-tree-sitter/src/server/mod.rs
> +mod fifo;
Please let that in `server.rs`.

2024-02-16 23:29 UTC, phaazon commented on kak-tree-sitter/src/server/mod.rs
> +    // self.disconnect_sessions();
What do you mean with this?

2024-02-16 23:29 UTC, phaazon commented on kak-tree-sitter/src/server/runtime_dir.rs
> +  pub fn display(&self) -> std::path::Display<'_> {
```suggestion
  pub fn display(&self) -> impl '_ + Display {
```

2024-02-16 23:29 UTC, phaazon commented on kak-tree-sitter/src/server/socket.rs
> +  /// Register the Unix handler to a Poll.
You named that socket handler; it’s not unix handler anymore.

2024-02-16 23:29 UTC, phaazon commented on runtime/queries/cpp/highlights.scm
> +
What are those?

2024-02-17 00:04 UTC, topisani commented
> - You renamed / moved a lot of things and I struggle to understand why. I think it’s not needed _for now_ and you should probably focus on implementing a feature. You moved a lot of symbols that have nothing to do with textobjects, making reviewing longer and harder, and breaking a bit history search (i.e. I very often `git blame` inside my editor, and seeing the same commit all over the place is not good).

I didn't originally do that with an intent to merge it, I was mainly just playing around with the codebase for my own use. I then ended up implementing some features on top of it. I should probably have marked this PR as a draft.

I'll try to split it out into some separate feature commits without the unnecessary refactorings.

2024-02-17 00:06 UTC, topisani commented on kak-tree-sitter/rc/base.kak
> +}
To only request highlighting when the timestamp has changed. Without using this, we would have to use a shell block to check the timestamp, which would start a new process on every NormalIdle.
I know it's very hacky, but It solves the problem pretty well, and I see no reason why it shouldn't continue to work reliably

2024-02-17 00:09 UTC, topisani commented on runtime/queries/cpp/highlights.scm
> +
Documentation comments in cpp. Like in rust, you can do `/// ` to make a documentation comment, that's then picked up by systems like doxygen. `/** */` has the same effect

2024-02-22 00:34 UTC, closed without merging